Add Mall.TV
kodi-czsk/repository pull request #45
Opened 2018-10-12 20:53 UTC by koperfieldcz

2018-10-16 10:14 UTC, maxo123123 commented
tesim sa na pridanie mall tv

2018-10-17 06:15 UTC, kapitan-iglu requested changes
Po kozmetickej uprave suhlasim so zaclenenim noveho pluginu.

2018-10-17 06:15 UTC, kapitan-iglu commented on addons.py
> +	"plugin.video.mall.tv"
Zachovat sposob odsadzovania 4mi medzerami:
```suggestion
    "plugin.video.mall.tv"
```

2018-10-17 11:57 UTC, koperfieldcz commented on addons.py
> +	"plugin.video.mall.tv"
Děkuji za upozornění. Zřejmě chyba editoru.

2018-10-17 12:51 UTC, kapitan-iglu approved these changes
Plugin som otestoval a funguje. Po obsahovej stranke navazuje na Stream, takze sem ten plugin urcite patri. 

@lzoubek, @E000001, @mx3L, @lubo: prosim o zaclenenie

2018-10-19 13:06 UTC, lzoubek commented
@kapitan-iglu diky za review @koperfieldcz diky za plugin

2018-10-19 13:06 UTC, merged

2018-10-25 19:44 UTC, koudi commented
Ahoj, uz nekolik dni nedoslo k aktualizaci pluginu v repositari, muzete se na to prosim podivat?

2018-10-28 07:41 UTC, bbaronSVK commented
@lzoubek @lubo naozaj sa neupdatuje repozitar. Ani stream cinema sa neupdatol v repozitari. Mozete to prosim pozriet?

2018-10-29 08:27 UTC, lzoubek commented
@bbaronSVK opraveno

2018-10-29 09:24 UTC, bbaronSVK commented
dik